# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "numpy",
#     "xarray",
#     "netcdf4",
# ]
# ///
"""Reproducible synthetic fixtures for the core plugin's verification layer.

Session 2 per SPECIFICATION.md v0.5.1 §6 (fixtures policy): synthetic
fixtures are generated by this script, deterministically, and the .nc files
are never committed. Run `python make_fixtures.py` (or `uv run`) from any
directory; files land beside this script.

Fixtures:
- era5like_t2m.nc: ERA5-like monthly 2 m temperature, 5 degree global grid,
  1985-2024, with known structure (see make_era5like_t2m docstring).
  Session 4 adds the bad-data variant (unmasked sentinels, impossible
  values, a 6-month gap) in this same script.
"""

from pathlib import Path

import numpy as np
import xarray as xr

HERE = Path(__file__).resolve().parent
SEED = 20260704

# Known structure of era5like_t2m, asserted by golden notebooks:
TREND_K_PER_DECADE = 0.20   # imposed global-mean linear trend
BASE_GLOBAL_MEAN_K = 287.5  # approximate area-weighted mean, start of record


def _build_era5like() -> xr.Dataset:
    """ERA5-like monthly t2m: zonal structure + seasonal cycle + trend + AR(1) noise.

    Composition, all deterministic under SEED:
    - zonal mean structure: warm equator, cold poles,
      t(lat) = 302 K - 40 K * sin^2(lat)
    - seasonal cycle: amplitude growing with |lat| (1 K equator, 14 K poles),
      opposite phase per hemisphere, peak boreal July
    - trend: 0.20 K/decade globally uniform (TREND_K_PER_DECADE)
    - noise: AR(1) in time per cell, phi = 0.5, innovation sigma = 0.6 K

    The zonal structure makes unweighted spatial means biased several K cold
    against the correct cos(lat)-weighted mean, so weighting mistakes are
    detectable, and the imposed trend gives Mann-Kendall a known answer.
    """
    rng = np.random.default_rng(SEED)

    lat = np.arange(-87.5, 88.0, 5.0)
    lon = np.arange(2.5, 358.0, 5.0)
    time = xr.date_range("1985-01-01", "2024-12-01", freq="MS", use_cftime=False)
    nt, ny, nx = len(time), len(lat), len(lon)

    latr = np.deg2rad(lat)
    zonal = 302.0 - 40.0 * np.sin(latr) ** 2                      # (ny,)
    amp = 1.0 + 13.0 * np.sin(latr) ** 2                          # (ny,)
    month = np.asarray(time.month)
    phase = np.cos(2 * np.pi * (month - 7) / 12.0)                # (nt,) peak July
    hemis = np.sign(lat)                                          # (ny,) SH flips phase
    seasonal = phase[:, None] * (amp * hemis)[None, :]            # (nt, ny)

    years = (np.arange(nt) / 12.0)
    trend = (TREND_K_PER_DECADE / 10.0) * years                   # (nt,)

    noise = np.empty((nt, ny, nx), dtype=np.float64)
    innov = rng.normal(0.0, 0.6, size=(nt, ny, nx))
    noise[0] = innov[0]
    for k in range(1, nt):
        noise[k] = 0.5 * noise[k - 1] + innov[k]

    data = (zonal[None, :, None]
            + seasonal[:, :, None]
            + trend[:, None, None]
            + noise).astype(np.float32)

    ds = xr.Dataset(
        {
            "t2m": (
                ("time", "lat", "lon"),
                data,
                {
                    "units": "K",
                    "long_name": "2 metre temperature",
                    "standard_name": "air_temperature",
                },
            )
        },
        coords={
            "time": ("time", time, {}),
            "lat": ("lat", lat, {"units": "degrees_north", "standard_name": "latitude"}),
            "lon": ("lon", lon, {"units": "degrees_east", "standard_name": "longitude"}),
        },
        attrs={
            "title": "Synthetic ERA5-like monthly 2 m temperature fixture",
            "source": f"core/verification/fixtures/make_fixtures.py, seed {SEED}",
            "note": (
                "Synthetic data for testing only; not ERA5. Known structure: "
                f"trend {TREND_K_PER_DECADE} K/decade, zonal 302-40*sin^2(lat) K, "
                "seasonal amplitude 1-14 K by latitude, AR(1) noise phi=0.5."
            ),
            "Conventions": "CF-1.8",
            "license": "public domain (synthetic)",
        },
    )
    return ds


def make_era5like_t2m(path: Path) -> xr.Dataset:
    ds = _build_era5like()
    ds.to_netcdf(path, encoding={"t2m": {"zlib": True, "complevel": 4}})
    return ds


# Bad-data variant (Session 4, for the QC behavior tests). Defect
# parameters are documented HERE and in the fixtures README, deliberately
# not in the file's own attributes, so QC tests stay honest.
BAD_SENTINEL = -9999.0
BAD_IMPOSSIBLE_K = 400.0                     # above every hard bound for t2m
BAD_IMPOSSIBLE_IDX = (240, 18, 36)           # 2005-01, near-equator cell
BAD_GAP = ("2003-03-01", "2003-08-31")       # six consecutive months, all NaN
BAD_N_SENTINELS = 300                        # scattered cell-months, 1995-1999


def make_bad_data(path: Path) -> xr.Dataset:
    """era5like field with three injected defects for the six QC checks:

    1. unmasked sentinels: BAD_N_SENTINELS cell-months set to -9999.0 with
       no _FillValue/missing_value advertising them (they decode as data);
    2. one impossible value: 400 K at BAD_IMPOSSIBLE_IDX;
    3. a six-month all-NaN gap: BAD_GAP inclusive.

    Sentinels are drawn from 1995-1999 so they never collide with the gap
    or the impossible value. Attributes intentionally do not mention the
    defects.
    """
    ds = _build_era5like()
    data = ds.t2m.values
    rng = np.random.default_rng(SEED + 1)

    years = ds.time.dt.year.values
    ok_t = np.where((years >= 1995) & (years <= 1999))[0]
    it = rng.choice(ok_t, BAD_N_SENTINELS)
    iy = rng.integers(0, ds.lat.size, BAD_N_SENTINELS)
    ix = rng.integers(0, ds.lon.size, BAD_N_SENTINELS)
    data[it, iy, ix] = BAD_SENTINEL

    data[BAD_IMPOSSIBLE_IDX] = BAD_IMPOSSIBLE_K

    gap = (ds.time >= np.datetime64(BAD_GAP[0])) & (ds.time <= np.datetime64(BAD_GAP[1]))
    data[np.where(gap.values)[0], :, :] = np.nan

    ds.attrs["title"] = "Synthetic monthly 2 m temperature test data"
    ds.attrs["note"] = "Synthetic data for testing only; not ERA5."
    ds.to_netcdf(path, encoding={"t2m": {"zlib": True, "complevel": 4}})
    return ds


def reference_stats(ds: xr.Dataset) -> dict:
    """Reference numbers golden notebooks and behavior tests check against."""
    w = np.cos(np.deg2rad(ds.lat))
    gm = ds.t2m.weighted(w).mean(("lat", "lon"))
    gm_unweighted = ds.t2m.mean(("lat", "lon"))
    fit = np.polyfit(np.arange(gm.size) / 120.0, gm.values, 1)  # per decade
    return {
        "weighted_mean_K": float(gm.mean()),
        "unweighted_mean_K": float(gm_unweighted.mean()),
        "weighting_bias_K": float(gm_unweighted.mean() - gm.mean()),
        "fitted_trend_K_per_decade": float(fit[0]),
    }


def main() -> None:
    out = HERE / "era5like_t2m.nc"
    ds = make_era5like_t2m(out)
    stats = reference_stats(ds)
    print(f"wrote {out} ({out.stat().st_size / 1e6:.1f} MB)")
    for k, v in stats.items():
        print(f"  {k}: {v:.3f}")
    assert abs(stats["fitted_trend_K_per_decade"] - TREND_K_PER_DECADE) < 0.05, \
        "fitted trend drifted from the imposed trend"
    assert stats["weighting_bias_K"] < -1.0, \
        "unweighted mean should be biased cold by more than 1 K"

    bad_out = HERE / "era5like_t2m_bad.nc"
    bad = make_bad_data(bad_out)
    v = bad.t2m.values
    n_sent = int((v == BAD_SENTINEL).sum())
    gap = (bad.time >= np.datetime64(BAD_GAP[0])) & (bad.time <= np.datetime64(BAD_GAP[1]))
    gap_all_nan = bool(np.isnan(v[np.where(gap.values)[0]]).all())
    print(f"wrote {bad_out} ({bad_out.stat().st_size / 1e6:.1f} MB)")
    print(f"  sentinels: {n_sent}, max value: {np.nanmax(v):.1f} K, "
          f"gap {BAD_GAP[0]}..{BAD_GAP[1]} all-NaN: {gap_all_nan}")
    assert 0 < n_sent <= BAD_N_SENTINELS, "sentinel injection failed"
    assert float(np.nanmax(v)) == BAD_IMPOSSIBLE_K, "impossible value missing"
    assert gap_all_nan and int(gap.sum()) == 6, "gap injection failed"

    roundtrip = xr.open_dataset(bad_out)
    assert float(roundtrip.t2m.min()) == BAD_SENTINEL, \
        "sentinels must survive the round trip unmasked"


if __name__ == "__main__":
    main()
