# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "numpy",
#     "xarray",
#     "netcdf4",
# ]
# ///
"""Reproducible synthetic fixtures for the core plugin's verification layer.

Session 2 per SPECIFICATION.md v0.5.1 §6 (fixtures policy): synthetic
fixtures are generated by this script, deterministically, and the .nc files
are never committed. Run `python make_fixtures.py` (or `uv run`) from any
directory; files land beside this script.

Fixtures:
- era5like_t2m.nc: ERA5-like monthly 2 m temperature, 5 degree global grid,
  1985-2024, with known structure (see make_era5like_t2m docstring).
  Session 4 adds the bad-data variant (unmasked sentinels, impossible
  values, a 6-month gap) in this same script.
"""

from pathlib import Path

import numpy as np
import xarray as xr

HERE = Path(__file__).resolve().parent
SEED = 20260704

# Known structure of era5like_t2m, asserted by golden notebooks:
TREND_K_PER_DECADE = 0.20   # imposed global-mean linear trend
BASE_GLOBAL_MEAN_K = 287.5  # approximate area-weighted mean, start of record


def make_era5like_t2m(path: Path) -> xr.Dataset:
    """ERA5-like monthly t2m: zonal structure + seasonal cycle + trend + AR(1) noise.

    Composition, all deterministic under SEED:
    - zonal mean structure: warm equator, cold poles,
      t(lat) = 302 K - 40 K * sin^2(lat)
    - seasonal cycle: amplitude growing with |lat| (1 K equator, 14 K poles),
      opposite phase per hemisphere, peak boreal July
    - trend: 0.20 K/decade globally uniform (TREND_K_PER_DECADE)
    - noise: AR(1) in time per cell, phi = 0.5, innovation sigma = 0.6 K

    The zonal structure makes unweighted spatial means biased several K cold
    against the correct cos(lat)-weighted mean, so weighting mistakes are
    detectable, and the imposed trend gives Mann-Kendall a known answer.
    """
    rng = np.random.default_rng(SEED)

    lat = np.arange(-87.5, 88.0, 5.0)
    lon = np.arange(2.5, 358.0, 5.0)
    time = xr.date_range("1985-01-01", "2024-12-01", freq="MS", use_cftime=False)
    nt, ny, nx = len(time), len(lat), len(lon)

    latr = np.deg2rad(lat)
    zonal = 302.0 - 40.0 * np.sin(latr) ** 2                      # (ny,)
    amp = 1.0 + 13.0 * np.sin(latr) ** 2                          # (ny,)
    month = np.asarray(time.month)
    phase = np.cos(2 * np.pi * (month - 7) / 12.0)                # (nt,) peak July
    hemis = np.sign(lat)                                          # (ny,) SH flips phase
    seasonal = phase[:, None] * (amp * hemis)[None, :]            # (nt, ny)

    years = (np.arange(nt) / 12.0)
    trend = (TREND_K_PER_DECADE / 10.0) * years                   # (nt,)

    noise = np.empty((nt, ny, nx), dtype=np.float64)
    innov = rng.normal(0.0, 0.6, size=(nt, ny, nx))
    noise[0] = innov[0]
    for k in range(1, nt):
        noise[k] = 0.5 * noise[k - 1] + innov[k]

    data = (zonal[None, :, None]
            + seasonal[:, :, None]
            + trend[:, None, None]
            + noise).astype(np.float32)

    ds = xr.Dataset(
        {
            "t2m": (
                ("time", "lat", "lon"),
                data,
                {
                    "units": "K",
                    "long_name": "2 metre temperature",
                    "standard_name": "air_temperature",
                },
            )
        },
        coords={
            "time": ("time", time, {}),
            "lat": ("lat", lat, {"units": "degrees_north", "standard_name": "latitude"}),
            "lon": ("lon", lon, {"units": "degrees_east", "standard_name": "longitude"}),
        },
        attrs={
            "title": "Synthetic ERA5-like monthly 2 m temperature fixture",
            "source": f"core/verification/fixtures/make_fixtures.py, seed {SEED}",
            "note": (
                "Synthetic data for testing only; not ERA5. Known structure: "
                f"trend {TREND_K_PER_DECADE} K/decade, zonal 302-40*sin^2(lat) K, "
                "seasonal amplitude 1-14 K by latitude, AR(1) noise phi=0.5."
            ),
            "Conventions": "CF-1.8",
            "license": "public domain (synthetic)",
        },
    )
    ds.to_netcdf(path, encoding={"t2m": {"zlib": True, "complevel": 4}})
    return ds


def reference_stats(ds: xr.Dataset) -> dict:
    """Reference numbers golden notebooks and behavior tests check against."""
    w = np.cos(np.deg2rad(ds.lat))
    gm = ds.t2m.weighted(w).mean(("lat", "lon"))
    gm_unweighted = ds.t2m.mean(("lat", "lon"))
    fit = np.polyfit(np.arange(gm.size) / 120.0, gm.values, 1)  # per decade
    return {
        "weighted_mean_K": float(gm.mean()),
        "unweighted_mean_K": float(gm_unweighted.mean()),
        "weighting_bias_K": float(gm_unweighted.mean() - gm.mean()),
        "fitted_trend_K_per_decade": float(fit[0]),
    }


def main() -> None:
    out = HERE / "era5like_t2m.nc"
    ds = make_era5like_t2m(out)
    stats = reference_stats(ds)
    print(f"wrote {out} ({out.stat().st_size / 1e6:.1f} MB)")
    for k, v in stats.items():
        print(f"  {k}: {v:.3f}")
    assert abs(stats["fitted_trend_K_per_decade"] - TREND_K_PER_DECADE) < 0.05, \
        "fitted trend drifted from the imposed trend"
    assert stats["weighting_bias_K"] < -1.0, \
        "unweighted mean should be biased cold by more than 1 K"


if __name__ == "__main__":
    main()
