#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy", "xarray", "netcdf4", "pymannkendall", "pyyaml"]
# ///
"""The reference attested computation of the foundation capability: the
global-mean temperature trend of the synthetic fixture, with a receipt
that names the capability release and the runtime that ran it.

This is the sanctioned executor (OKF v0.2 section 10, as the provider
bundle's computations practise it). It regenerates the fixture
deterministically, applies the analysis the golden notebook asserts
(area-weighted global mean, anomalies against 1991-2020, Sen's slope
with the Hamed-Rao modified Mann-Kendall test, a moving-block bootstrap
interval with a fixed seed) and writes one receipt. The receipt carries
the sha256 of this file, the fixture's and its generator's digests, the
capability's name, version and release lock read from the package
beside this script, the runtime named by the caller, the bound
parameters, the results with the anomaly series they follow from, and
the mutation evidence (the unweighted mean must read more than 5 K
cold, or the run aborts receiptless). trend_attester.py verifies a
receipt from any runtime against this file, the regenerated fixture
and its own recomputation; no language model is in either path.

  trend_computation.py --runtime NAME [--runtime-version V] [--out RECEIPT]
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import pymannkendall as pmk
import xarray as xr
import yaml

HERE = Path(__file__).resolve().parent
PACKAGE_ROOT = HERE.parents[2]
FIXTURES = PACKAGE_ROOT / "verification" / "fixtures"
COMPUTATION = "skills/basic-statistics/scripts/trend_computation.py"
SEED = 20260704
BLOCK = 12
RESAMPLES = 500
BASELINE = ("1991-01-01", "2020-12-31")
WEIGHTING_BIAS_BAR_K = -5.0


def sha256_file(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def value_digest(value) -> str:
    return "sha256:" + hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()


def capability_identity(root: Path) -> dict:
    """name, version and release lock of the package this script ships in."""
    pkg = yaml.safe_load((root / ".osp" / "package.yaml").read_text(encoding="utf-8"))["package"]
    lock_path = root / ".osp" / "release-lock.json"
    lock = json.loads(lock_path.read_text(encoding="utf-8")) if lock_path.is_file() else None
    return {"name": pkg["name"], "version": str(pkg["version"]),
            "release_lock": value_digest(lock) if lock is not None else None}


def fixture(path: Path) -> Path:
    """The synthetic fixture, regenerated by its generator when absent."""
    if not path.exists():
        spec = importlib.util.spec_from_file_location("make_fixtures", FIXTURES / "make_fixtures.py")
        mf = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mf)
        mf.make_era5like_t2m(path)
    return path


def analysis(ds: xr.Dataset) -> dict:
    """The golden notebook's chain, as numbers: QC, weighted mean, anomalies,
    trend, interval, and the weighting detector."""
    vmin, vmax = float(ds.t2m.min()), float(ds.t2m.max())
    for sentinel in (-9999.0, -999.0, -32767.0, 1e20, 9.96921e36):
        if bool((ds.t2m == sentinel).any()):
            raise SystemExit(f"unmasked sentinel {sentinel} in the fixture")
    if int(ds.t2m.isnull().sum()) != 0 or not (180.0 < vmin and vmax < 340.0):
        raise SystemExit("the fixture failed the clean-data checks")
    w = np.cos(np.deg2rad(ds.lat))
    gm = ds.t2m.weighted(w).mean(["lat", "lon"])
    unweighted = float(ds.t2m.mean(["lat", "lon"]).mean())
    weighted_mean = float(gm.mean())
    clim = gm.sel(time=slice(*BASELINE)).groupby("time.month").mean()
    anom = (gm.groupby("time.month") - clim).values.astype(float)
    return {"weighted_mean_k": weighted_mean, "unweighted_mean_k": unweighted,
            "anomaly_k": [float(v) for v in anom], "n_months": int(anom.size),
            **trend(anom)}


def trend(y: np.ndarray) -> dict:
    """Sen's slope per decade under the Hamed-Rao test, and the moving-block
    bootstrap interval on the OLS slope; recomputable from the series."""
    res = pmk.hamed_rao_modification_test(y)
    sen = float(res.slope * 120)
    t = np.arange(y.size) / 120.0
    slope_hat, intercept = np.polyfit(t, y, 1)
    resid = y - (slope_hat * t + intercept)
    rng = np.random.default_rng(SEED)
    n = y.size
    n_blocks = int(np.ceil(n / BLOCK))
    slopes = np.empty(RESAMPLES)
    for i in range(RESAMPLES):
        starts = rng.integers(0, n - BLOCK, n_blocks)
        boot = np.concatenate([resid[s:s + BLOCK] for s in starts])[:n]
        slopes[i] = np.polyfit(t, slope_hat * t + intercept + boot, 1)[0]
    lo, hi = np.percentile(slopes, [2.5, 97.5])
    return {"mk_trend": res.trend, "mk_p": float(res.p), "sen_k_per_decade": sen,
            "ci95_k_per_decade": [float(lo), float(hi)]}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runtime", required=True, help="the runtime that ran this (claude-code, claude-cowork, openai-codex, ...)")
    ap.add_argument("--runtime-version", default=None)
    ap.add_argument("--out", default="receipt.json")
    ap.add_argument("--fixture", default=str(FIXTURES / "era5like_t2m.nc"))
    args = ap.parse_args()

    fx = fixture(Path(args.fixture))
    generator = FIXTURES / "make_fixtures.py"
    ds = xr.open_dataset(fx)
    results = analysis(ds)
    bias = results["unweighted_mean_k"] - results["weighted_mean_k"]
    if not bias < WEIGHTING_BIAS_BAR_K:
        raise SystemExit(f"weighting detector not tripped (bias {bias:.2f} K); no receipt")
    receipt = {
        "computation": COMPUTATION,
        "code_sha256": sha256_file(Path(__file__).resolve()),
        "capability": capability_identity(PACKAGE_ROOT),
        "runtime": {"name": args.runtime, "version": args.runtime_version},
        "generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "data": {"fixture": fx.name, "sha256": sha256_file(fx), "generator": "verification/fixtures/make_fixtures.py",
                 "generator_sha256": sha256_file(generator), "seed": SEED},
        "bound_parameters": {"baseline": list(BASELINE), "trend_test": "hamed_rao_modification_test",
                             "slope": "sen", "interval": "moving-block bootstrap on the OLS slope",
                             "block_length_months": BLOCK, "resamples": RESAMPLES, "seed": SEED},
        "results": results,
        "mutation_evidence": {"unweighted_bias_k": bias, "bar_k": WEIGHTING_BIAS_BAR_K, "caught": True},
        "caveats": ["synthetic fixture (public domain), not observations: the numbers verify the chain, not the climate",
                    "the anomaly series is carried at full precision so the trend and its interval are recomputable from the receipt"],
    }
    receipt["run_id"] = value_digest({k: v for k, v in receipt.items() if k != "generated_utc"})[:23]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    r = results
    half = (r["ci95_k_per_decade"][1] - r["ci95_k_per_decade"][0]) / 2
    print(f"{receipt['capability']['name']} {receipt['capability']['version']} on {args.runtime}: "
          f"trend {r['sen_k_per_decade']:.3f} +/- {half:.3f} K/decade (95% CI, block bootstrap), "
          f"Hamed-Rao MK p = {r['mk_p']:.1e}; receipt {out} run {receipt['run_id']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
